package com.aituber.poc.character.live2d

data class Live2DNativeSnapshot(
    val runtimeLoaded: Boolean,
    val coreLoaded: Boolean,
    val modelLoaded: Boolean,
    val mouthParameterFound: Boolean,
    val inputMouthOpen: Float,
    val appliedMouthOpen: Float,
    val leftEyeParameterStatus: String,
    val rightEyeParameterStatus: String,
    val inputLeftEyeOpen: Float,
    val inputRightEyeOpen: Float,
    val appliedLeftEyeOpen: Float,
    val appliedRightEyeOpen: Float,
    val breathParameterStatus: String,
    val inputBreathNormalized: Float,
    val appliedBreathValue: Float,
    val breathMin: Float,
    val breathMax: Float,
    val breathDefault: Float,
    val renderFps: Double,
    val nativeFrameCount: Long,
    val surfaceWidth: Int,
    val surfaceHeight: Int,
    val modelName: String,
    val mouthParameterId: String,
    val lastError: String,
    val textureCount: Int,
    val texturesLoaded: Int,
    val lastTexturePath: String,
    val lastTextureError: String,
    val glTextureIds: String,
    val poseFile: String,
    val poseLoaded: Boolean,
    val poseActive: Boolean
) {
    companion object {
        fun unavailable(reason: String) = Live2DNativeSnapshot(
            runtimeLoaded = false,
            coreLoaded = false,
            modelLoaded = false,
            mouthParameterFound = false,
            inputMouthOpen = 0f,
            appliedMouthOpen = 0f,
            leftEyeParameterStatus = "UNAVAILABLE",
            rightEyeParameterStatus = "UNAVAILABLE",
            inputLeftEyeOpen = 1f,
            inputRightEyeOpen = 1f,
            appliedLeftEyeOpen = 1f,
            appliedRightEyeOpen = 1f,
            breathParameterStatus = "UNAVAILABLE",
            inputBreathNormalized = 0.5f,
            appliedBreathValue = 0.5f,
            breathMin = 0f,
            breathMax = 1f,
            breathDefault = 0.5f,
            renderFps = 0.0,
            nativeFrameCount = 0L,
            surfaceWidth = 0,
            surfaceHeight = 0,
            modelName = "Haru",
            mouthParameterId = "ParamMouthOpenY",
            lastError = reason,
            textureCount = 0,
            texturesLoaded = 0,
            lastTexturePath = "n/a",
            lastTextureError = reason,
            glTextureIds = "[]",
            poseFile = "n/a",
            poseLoaded = false,
            poseActive = false
        )
    }
}
